Try making Habitica API calls multiple times
The error I've been seeing sometimes is:

	urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='habitica.com', port=443):
	Max retries exceeded with url: /api/v3/user/class/cast/smash?targetId=01234567-89ab-cdef-fedc-ba9876543210
	(Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))

There is probably a smarter way of avoiding this with requests directly.
But this is my low-tech solution when something goes wrong:
wait 20 seconds and try again, up to 5 times by default.